apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: appnodepool
spec:
  disruption:
    budgets:
    - nodes: 100%
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  template:
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: karpenter.azure.com/sku-family
        operator: In
        values:
        - D
      - key: karpenter.azure.com/sku-name
        operator: In
        values:
        - Standard_D2as_v5
        - Standard_D4as_v5
        - Standard_D8as_v5
        - Standard_D16as_v5
        - Standard_D32as_v5
      taints:
        - key: CriticalAddonsOnly
          effect: NoSchedule
          value: "true"
        - key: deployment
          effect: NoSchedule
          value: "aqs-app-pool"